#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    lift,           sensorPotentiometer)
#pragma config(Sensor, in2,    vertibar,       sensorPotentiometer)
#pragma config(Sensor, in3,    gyro,           sensorGyro)
#pragma config(Sensor, in4,    mobogo,         sensorPotentiometer)
#pragma config(Sensor, in5,    autonselect,    sensorPotentiometer)
#pragma config(Sensor, I2C_1,  LeftDrive,      sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  RightDrive,     sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           lVertibar,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rGoal,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           lDrive,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rDrive,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           rVertibar,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           lLift,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rLift,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

#include "lift.h"
#include "lift.c"

#define AUTONOMOUS_GOAL 10
#define BLUE 1

#if !BLUE

#if AUTONOMOUS_GOAL==0
#include "defensiveauto.c"
#elif AUTONOMOUS_GOAL==20
#include "twentyauto.c"
#elif AUTONOMOUS_GOAL==10
#include "tenauto.c"
#elif AUTONOMOUS_GOAL==27
#include "supportauto.c"
#endif

#elif BLUE

#if AUTONOMOUS_GOAL==0
#include "defensiveauto.c"
#elif AUTONOMOUS_GOAL==20
#include "bluetwenty.c"
#elif AUTONOMOUS_GOAL==10
#include "blueten.c"
#elif AUTONOMOUS_GOAL==27
#include "bluesupport.c"
#endif

#endif


void pre_auton() {
	SensorType[gyro] = sensorNone;
	wait1Msec(1000);
	SensorType[gyro] = sensorGyro;
	delay(1100);
	SensorValue[gyro] = 0;
}

task autonomous() {
#if AUTONOMOUS_GOAL==10
	ten();
#elif AUTONOMOUS_GOAL==20
	twenty();
#elif AUTONOMOUS_GOAL==27
	twentyseven();
#elif AUTONOMOUS_GOAL==0
	defensive();
#endif
}

task usercontrol()
{
	resetDriveIME();
	//current number of times claw has opened; used to keep track of current state
	int clawCounter = 0;

	//number of cones on mogo, referenced in autostack function
	int coneCounter = 0;

	//used to detect change of state of claw input button
	bool claw = false;

	while(true) {
		motor[port4] = -vexRT[Ch2];
		motor[port5] = vexRT[Ch3];

		//lift
		motor[port9] = -(100 * vexRT[Btn5U] + -100 * vexRT[Btn5D] + 20);
		motor[port8] = 100 * vexRT[Btn5U] + -100 * vexRT[Btn5D] + 20;

		//vertibar
		motor[port7] = -(100 * vexRT[Btn6U] + -100 * vexRT[Btn6D]);
		motor[port3] = -(100 * vexRT[Btn6U] + -100 * vexRT[Btn6D]);


		//mobileBtn7D
		motor[port2] = 100 * vexRT[Btn7U] + -90 * vexRT[Btn7L];



		// counter control
		if (vexRT[Btn8L] && coneCounter > 0) {
			waitUntil(!vexRT[Btn8L]);
			--coneCounter;
			} else if (vexRT[Btn8R]) {
			waitUntil(!vexRT[Btn8R]);
			++coneCounter;
		}

		if(vexRT[Btn8U]) coneCounter = 0;

		if(vexRT[Btn7D]) {
			if(!claw) {
				++clawCounter;
				claw = true;
				if(clawCounter % 3 == 0) {
					motor[port6] = -100;
					wait1Msec(200);
					motor[port6] = -20;
				}
				else if(clawCounter % 3 == 1) {
					motor[port6] = 100;
					wait1Msec(200);
					motor[port6] = 30;
				}

			}
		}
		else {
			claw = false;
		}
	}

}
